name: Sync code

on:
  push:
    branches:
    - main
  schedule:
    - cron: '0 2 * * *'
    
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: push
      run: |
        wget https://cn.wordpress.org/latest-zh_CN.zip
        unzip latest-zh_CN.zip
        mv ./wordpress/* ./
        rm -rf wordpress
        
    - name: Upload
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add .
        git push
        
